var hierarchy =
[
    [ "Traveller_Server.Models.DataClasses.ActivityLog", "class_traveller___server_1_1_models_1_1_data_classes_1_1_activity_log.html", null ],
    [ "Traveller_Server.Models.DataClasses.Alert", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert.html", null ],
    [ "Traveller_Server.Models.DataClasses.AlertRatingInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert_rating_info.html", null ],
    [ "Traveller_Server.Services.AuthMessageSenderOptions", "class_traveller___server_1_1_services_1_1_auth_message_sender_options.html", null ],
    [ "Traveller_Server.Models.DataClasses.AuthResponse", "class_traveller___server_1_1_models_1_1_data_classes_1_1_auth_response.html", null ],
    [ "Controller", null, [
      [ "Traveller_Server.Controllers.ActivityLogsController", "class_traveller___server_1_1_controllers_1_1_activity_logs_controller.html", null ],
      [ "Traveller_Server.Controllers.CourseRoutesController", "class_traveller___server_1_1_controllers_1_1_course_routes_controller.html", null ],
      [ "Traveller_Server.Controllers.CoursesController", "class_traveller___server_1_1_controllers_1_1_courses_controller.html", null ],
      [ "Traveller_Server.Controllers.HomeController", "class_traveller___server_1_1_controllers_1_1_home_controller.html", null ],
      [ "Traveller_Server.Controllers.ResetPasswordLogsController", "class_traveller___server_1_1_controllers_1_1_reset_password_logs_controller.html", null ],
      [ "Traveller_Server.Controllers.RoutesController", "class_traveller___server_1_1_controllers_1_1_routes_controller.html", null ],
      [ "Traveller_Server.Controllers.StopsController", "class_traveller___server_1_1_controllers_1_1_stops_controller.html", null ],
      [ "Traveller_Server.Controllers.UserStatusController", "class_traveller___server_1_1_controllers_1_1_user_status_controller.html", null ],
      [ "Traveller_Server.Controllers.UserSuspensionsController", "class_traveller___server_1_1_controllers_1_1_user_suspensions_controller.html", null ],
      [ "Traveller_Server.Controllers.User_CourseController", "class_traveller___server_1_1_controllers_1_1_user___course_controller.html", null ],
      [ "Traveller_Server.Controllers.UsersController", "class_traveller___server_1_1_controllers_1_1_users_controller.html", null ]
    ] ],
    [ "ControllerBase", null, [
      [ "Traveller_Server.Controllers.ActivityLogsApiController", "class_traveller___server_1_1_controllers_1_1_activity_logs_api_controller.html", null ],
      [ "Traveller_Server.Controllers.AlertsApiController", "class_traveller___server_1_1_controllers_1_1_alerts_api_controller.html", null ],
      [ "Traveller_Server.Controllers.LinkedStopsApiController", "class_traveller___server_1_1_controllers_1_1_linked_stops_api_controller.html", null ],
      [ "Traveller_Server.Controllers.LocationsApiController", "class_traveller___server_1_1_controllers_1_1_locations_api_controller.html", null ],
      [ "Traveller_Server.Controllers.RoutesApiController", "class_traveller___server_1_1_controllers_1_1_routes_api_controller.html", null ],
      [ "Traveller_Server.Controllers.StatisticsApiController", "class_traveller___server_1_1_controllers_1_1_statistics_api_controller.html", null ],
      [ "Traveller_Server.Controllers.StopsApiController", "class_traveller___server_1_1_controllers_1_1_stops_api_controller.html", null ],
      [ "Traveller_Server.Controllers.TransportsApiController", "class_traveller___server_1_1_controllers_1_1_transports_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserApiController", "class_traveller___server_1_1_controllers_1_1_user_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserStatusApiController", "class_traveller___server_1_1_controllers_1_1_user_status_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserSuspensionsApiController", "class_traveller___server_1_1_controllers_1_1_user_suspensions_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UsersApiController", "class_traveller___server_1_1_controllers_1_1_users_api_controller.html", null ]
    ] ],
    [ "Traveller_Server.Models.DataClasses.Course", "class_traveller___server_1_1_models_1_1_data_classes_1_1_course.html", null ],
    [ "Traveller_Server.Models.DataClasses.CourseRoute", "class_traveller___server_1_1_models_1_1_data_classes_1_1_course_route.html", null ],
    [ "Traveller_Server.Models.ErrorViewModel", "class_traveller___server_1_1_models_1_1_error_view_model.html", null ],
    [ "IdentityDbContext", null, [
      [ "Traveller_Server.Data.Traveller_ServerContext", "class_traveller___server_1_1_data_1_1_traveller___server_context.html", null ]
    ] ],
    [ "IdentityUser", null, [
      [ "Traveller_Server.Models.DataClasses.User", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user.html", null ]
    ] ],
    [ "IEmailSender", null, [
      [ "Traveller_Server.Services.EmailSender", "class_traveller___server_1_1_services_1_1_email_sender.html", null ]
    ] ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.ExternalLoginModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_external_login_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.ForgotPasswordModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_forgot_password_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.LoginModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.LoginWith2faModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_with2fa_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.LoginWithRecoveryCodeModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_with_recovery_code_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ChangePasswordModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_change_password_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.DeletePersonalDataModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_delete_personal_data_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.EmailModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_email_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.EnableAuthenticatorModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_enable_authenticator_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.IndexModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_index_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.SetPasswordModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_set_password_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.RegisterModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_register_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.ResendEmailConfirmationModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_resend_email_confirmation_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.ResetPasswordModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_reset_password_model_1_1_input_model.html", null ],
    [ "Traveller_Server.JwtFeatures.JwtHandler", "class_traveller___server_1_1_jwt_features_1_1_jwt_handler.html", null ],
    [ "Traveller_Server.Models.DataClasses.LinkedStop", "class_traveller___server_1_1_models_1_1_data_classes_1_1_linked_stop.html", null ],
    [ "Traveller_Server.Models.DataClasses.Location", "class_traveller___server_1_1_models_1_1_data_classes_1_1_location.html", null ],
    [ "Migration", null, [
      [ "Traveller_Server.Migrations.Initial", "class_traveller___server_1_1_migrations_1_1_initial.html", null ]
    ] ],
    [ "ModelSnapshot", null, [
      [ "Traveller_Server.Migrations.Traveller_ServerContextModelSnapshot", "class_traveller___server_1_1_migrations_1_1_traveller___server_context_model_snapshot.html", null ]
    ] ],
    [ "PageModel", null, [
      [ "Traveller_Server.Areas.Identity.Pages.Account.AccessDeniedModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_access_denied_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ConfirmEmailChangeModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_confirm_email_change_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ConfirmEmailModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_confirm_email_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ExternalLoginModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_external_login_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ForgotPasswordConfirmation", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_forgot_password_confirmation.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ForgotPasswordModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_forgot_password_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LockoutModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_lockout_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LoginModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LoginWith2faModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_with2fa_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LoginWithRecoveryCodeModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_with_recovery_code_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LogoutModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_logout_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ChangePasswordModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_change_password_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.DeletePersonalDataModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_delete_personal_data_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.Disable2faModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_disable2fa_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.DownloadPersonalDataModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_download_personal_data_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.EmailModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_email_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.EnableAuthenticatorModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_enable_authenticator_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ExternalLoginsModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_external_logins_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.GenerateRecoveryCodesModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_generate_recovery_codes_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.IndexModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_index_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.PersonalDataModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_personal_data_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ResetAuthenticatorModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_reset_authenticator_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.SetPasswordModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_set_password_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ShowRecoveryCodesModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_show_recovery_codes_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.TwoFactorAuthenticationModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_two_factor_authentication_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.RegisterConfirmationModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_register_confirmation_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.RegisterModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_register_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ResendEmailConfirmationModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_resend_email_confirmation_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ResetPasswordConfirmationModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_reset_password_confirmation_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ResetPasswordModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_reset_password_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.ErrorModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_error_model.html", null ]
    ] ],
    [ "Traveller_Server.Program", "class_traveller___server_1_1_program.html", null ],
    [ "Traveller_Server.Models.DataClasses.ResetPasswordLog", "class_traveller___server_1_1_models_1_1_data_classes_1_1_reset_password_log.html", null ],
    [ "Traveller_Server.Models.DataClasses.Route", "class_traveller___server_1_1_models_1_1_data_classes_1_1_route.html", null ],
    [ "Traveller_Server.Models.DataClasses.Stop", "class_traveller___server_1_1_models_1_1_data_classes_1_1_stop.html", null ],
    [ "Traveller_Server.Models.DataClasses.TimeSpentWeek", "class_traveller___server_1_1_models_1_1_data_classes_1_1_time_spent_week.html", null ],
    [ "Traveller_Server.Models.DataClasses.Transport", "class_traveller___server_1_1_models_1_1_data_classes_1_1_transport.html", null ],
    [ "Traveller_Server.Models.DataClasses.User_Course", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user___course.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserChangeState", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_change_state.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserForAuthentication", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_for_authentication.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserResetPassword", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_reset_password.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserStatus", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_status.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserSuspension", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_suspension.html", null ]
];