var hierarchy =
[
    [ "Traveller_Server.Models.DataClasses.ActivityLog", "class_traveller___server_1_1_models_1_1_data_classes_1_1_activity_log.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFS.Agency", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_1_1_agency.html", null ],
    [ "Traveller_Server.Models.DataClasses.Alert", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert.html", null ],
    [ "Traveller_Server.Models.DataClasses.AlertRatingInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert_rating_info.html", null ],
    [ "Traveller_Server.Models.DataClasses.AlertVote", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert_vote.html", null ],
    [ "Traveller_Server.Models.DataClasses.AuthResponse", "class_traveller___server_1_1_models_1_1_data_classes_1_1_auth_response.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFS.CalendarDate", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_1_1_calendar_date.html", null ],
    [ "Traveller_Server.Controllers.GTFSRealtime.FeedMessagesApiController.ConfirmFeedMessage", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_feed_messages_api_controller_1_1_confirm_feed_message.html", null ],
    [ "Controller", null, [
      [ "Traveller_Server.Controllers.HomeController", "class_traveller___server_1_1_controllers_1_1_home_controller.html", null ],
      [ "Traveller_Server.Controllers.UserApiController", "class_traveller___server_1_1_controllers_1_1_user_api_controller.html", null ]
    ] ],
    [ "ControllerBase", null, [
      [ "Traveller_Server.Controllers.ActivityLogsApiController", "class_traveller___server_1_1_controllers_1_1_activity_logs_api_controller.html", null ],
      [ "Traveller_Server.Controllers.AlertVotesController", "class_traveller___server_1_1_controllers_1_1_alert_votes_controller.html", null ],
      [ "Traveller_Server.Controllers.AlertsApiController", "class_traveller___server_1_1_controllers_1_1_alerts_api_controller.html", null ],
      [ "Traveller_Server.Controllers.AuthApiController", "class_traveller___server_1_1_controllers_1_1_auth_api_controller.html", null ],
      [ "Traveller_Server.Controllers.CoursesApiController", "class_traveller___server_1_1_controllers_1_1_courses_api_controller.html", null ],
      [ "Traveller_Server.Controllers.CurrentlyBoardedUsersApiController", "class_traveller___server_1_1_controllers_1_1_currently_boarded_users_api_controller.html", null ],
      [ "Traveller_Server.Controllers.FavoritePlacesApiController", "class_traveller___server_1_1_controllers_1_1_favorite_places_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSControllers.AgenciesApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_controllers_1_1_agencies_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSControllers.CalendarDatesApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_controllers_1_1_calendar_dates_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSControllers.FeedInfosApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_controllers_1_1_feed_infos_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSControllers.RoutesApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_controllers_1_1_routes_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSControllers.ShapesApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_controllers_1_1_shapes_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSControllers.StopTimesApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_controllers_1_1_stop_times_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSControllers.StopsApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_controllers_1_1_stops_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSControllers.TripsApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_controllers_1_1_trips_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSRealtime.FeedEntitiesApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_feed_entities_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSRealtime.FeedHeadersApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_feed_headers_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSRealtime.FeedMessagesApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_feed_messages_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSRealtime.StopTimeUpdatesApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_stop_time_updates_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSRealtime.TripDescriptorsApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_trip_descriptors_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSRealtime.TripUpdatesApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_trip_updates_api_controller.html", null ],
      [ "Traveller_Server.Controllers.GTFSRealtime.VehiclePositionsApiController", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_vehicle_positions_api_controller.html", null ],
      [ "Traveller_Server.Controllers.KeyVaultController", "class_traveller___server_1_1_controllers_1_1_key_vault_controller.html", null ],
      [ "Traveller_Server.Controllers.LocationsApiController", "class_traveller___server_1_1_controllers_1_1_locations_api_controller.html", null ],
      [ "Traveller_Server.Controllers.StatisticsApiController", "class_traveller___server_1_1_controllers_1_1_statistics_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserBoardedInfoesApiController", "class_traveller___server_1_1_controllers_1_1_user_boarded_infoes_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserBoardingInfoesApiController", "class_traveller___server_1_1_controllers_1_1_user_boarding_infoes_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserLocationsApiController", "class_traveller___server_1_1_controllers_1_1_user_locations_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserRouteTrackingsApiController", "class_traveller___server_1_1_controllers_1_1_user_route_trackings_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserStatusApiController", "class_traveller___server_1_1_controllers_1_1_user_status_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserStopInfoesApiController", "class_traveller___server_1_1_controllers_1_1_user_stop_infoes_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UserSuspensionsApiController", "class_traveller___server_1_1_controllers_1_1_user_suspensions_api_controller.html", null ],
      [ "Traveller_Server.Controllers.User_CourseApiController", "class_traveller___server_1_1_controllers_1_1_user___course_api_controller.html", null ],
      [ "Traveller_Server.Controllers.UsersApiController", "class_traveller___server_1_1_controllers_1_1_users_api_controller.html", null ]
    ] ],
    [ "Traveller_Server.Models.DataClasses.Course", "class_traveller___server_1_1_models_1_1_data_classes_1_1_course.html", null ],
    [ "Traveller_Server.Models.DataClasses.CourseRoute", "class_traveller___server_1_1_models_1_1_data_classes_1_1_course_route.html", null ],
    [ "Traveller_Server.Models.DataClasses.CurrentlyBoardedUser", "class_traveller___server_1_1_models_1_1_data_classes_1_1_currently_boarded_user.html", null ],
    [ "Traveller_Server.Controllers.GTFSRealtime.FeedMessagesApiController.DelayMessageResponse", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_feed_messages_api_controller_1_1_delay_message_response.html", null ],
    [ "Traveller_Server.Models.ErrorViewModel", "class_traveller___server_1_1_models_1_1_error_view_model.html", null ],
    [ "Traveller_Server.Models.DataClasses.FavoritePlace", "class_traveller___server_1_1_models_1_1_data_classes_1_1_favorite_place.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFSRealtime.FeedEntity", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_realtime_1_1_feed_entity.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFSRealtime.FeedHeader", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_realtime_1_1_feed_header.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFS.FeedInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_1_1_feed_info.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFSRealtime.FeedMessage", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_realtime_1_1_feed_message.html", null ],
    [ "Traveller_Server.Controllers.GTFSControllers.TripsApiController.GoogleTripInfoMessage", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_controllers_1_1_trips_api_controller_1_1_google_trip_info_message.html", null ],
    [ "IdentityDbContext", null, [
      [ "Traveller_Server.Data.Traveller_ServerContext", "class_traveller___server_1_1_data_1_1_traveller___server_context.html", null ]
    ] ],
    [ "IdentityUser", null, [
      [ "Traveller_Server.Models.DataClasses.User", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user.html", null ]
    ] ],
    [ "IEmailSender", null, [
      [ "Traveller_Server.Services.EmailSender", "class_traveller___server_1_1_services_1_1_email_sender.html", null ]
    ] ],
    [ "Traveller_Server.AzureKeyVault.IKeyVaultManager", "interface_traveller___server_1_1_azure_key_vault_1_1_i_key_vault_manager.html", [
      [ "Traveller_Server.AzureKeyVault.KeyVaultManager", "class_traveller___server_1_1_azure_key_vault_1_1_key_vault_manager.html", null ]
    ] ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.ExternalLoginModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_external_login_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.ForgotPasswordModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_forgot_password_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.LoginModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.LoginWith2faModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_with2fa_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.LoginWithRecoveryCodeModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_with_recovery_code_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ChangePasswordModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_change_password_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.DeletePersonalDataModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_delete_personal_data_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.EmailModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_email_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.EnableAuthenticatorModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_enable_authenticator_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.IndexModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_index_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.SetPasswordModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_set_password_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.RegisterModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_register_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.ResendEmailConfirmationModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_resend_email_confirmation_model_1_1_input_model.html", null ],
    [ "Traveller_Server.Areas.Identity.Pages.Account.ResetPasswordModel.InputModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_reset_password_model_1_1_input_model.html", null ],
    [ "Traveller_Server.JwtFeatures.JwtHandler", "class_traveller___server_1_1_jwt_features_1_1_jwt_handler.html", null ],
    [ "Traveller_Server.Models.DataClasses.Location", "class_traveller___server_1_1_models_1_1_data_classes_1_1_location.html", null ],
    [ "Migration", null, [
      [ "Traveller_Server.Migrations.Initial", "class_traveller___server_1_1_migrations_1_1_initial.html", null ]
    ] ],
    [ "ModelSnapshot", null, [
      [ "Traveller_Server.Migrations.Traveller_ServerContextModelSnapshot", "class_traveller___server_1_1_migrations_1_1_traveller___server_context_model_snapshot.html", null ]
    ] ],
    [ "PageModel", null, [
      [ "Traveller_Server.Areas.Identity.Pages.Account.AccessDeniedModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_access_denied_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ConfirmEmailChangeModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_confirm_email_change_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ConfirmEmailModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_confirm_email_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ExternalLoginModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_external_login_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ForgotPasswordConfirmation", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_forgot_password_confirmation.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ForgotPasswordModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_forgot_password_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LockoutModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_lockout_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LoginModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LoginWith2faModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_with2fa_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LoginWithRecoveryCodeModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_login_with_recovery_code_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.LogoutModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_logout_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ChangePasswordModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_change_password_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.DeletePersonalDataModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_delete_personal_data_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.Disable2faModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_disable2fa_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.DownloadPersonalDataModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_download_personal_data_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.EmailModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_email_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.EnableAuthenticatorModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_enable_authenticator_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ExternalLoginsModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_external_logins_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.GenerateRecoveryCodesModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_generate_recovery_codes_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.IndexModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_index_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.PersonalDataModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_personal_data_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ResetAuthenticatorModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_reset_authenticator_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.SetPasswordModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_set_password_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.ShowRecoveryCodesModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_show_recovery_codes_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.Manage.TwoFactorAuthenticationModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage_1_1_two_factor_authentication_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.RegisterConfirmationModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_register_confirmation_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.RegisterModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_register_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ResendEmailConfirmationModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_resend_email_confirmation_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ResetPasswordConfirmationModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_reset_password_confirmation_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.Account.ResetPasswordModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_reset_password_model.html", null ],
      [ "Traveller_Server.Areas.Identity.Pages.ErrorModel", "class_traveller___server_1_1_areas_1_1_identity_1_1_pages_1_1_error_model.html", null ]
    ] ],
    [ "Traveller_Server.Program", "class_traveller___server_1_1_program.html", null ],
    [ "Traveller_Server.Models.DataClasses.ResetPasswordLog", "class_traveller___server_1_1_models_1_1_data_classes_1_1_reset_password_log.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFS.Route", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_1_1_route.html", null ],
    [ "Traveller_Server.Controllers.GTFSRealtime.FeedMessagesApiController.RouteTripInfoMessage", "class_traveller___server_1_1_controllers_1_1_g_t_f_s_realtime_1_1_feed_messages_api_controller_1_1_route_trip_info_message.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFS.Shape", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_1_1_shape.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFS.Stop", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_1_1_stop.html", null ],
    [ "Traveller_Server.Models.StopLinker", "class_traveller___server_1_1_models_1_1_stop_linker.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFS.StopTime", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_1_1_stop_time.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFSRealtime.StopTimeUpdate", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_realtime_1_1_stop_time_update.html", null ],
    [ "Traveller_Server.Models.DataClasses.TimeSpentWeek", "class_traveller___server_1_1_models_1_1_data_classes_1_1_time_spent_week.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFS.Trip", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_1_1_trip.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFSRealtime.TripDescriptor", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_realtime_1_1_trip_descriptor.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFSRealtime.TripUpdate", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_realtime_1_1_trip_update.html", null ],
    [ "Traveller_Server.Models.DataClasses.User_Course", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user___course.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserBoardedInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_boarded_info.html", null ],
    [ "Traveller_Server.Controllers.UserBoardedInfoesApiController.UserBoardedInfoMessage", "class_traveller___server_1_1_controllers_1_1_user_boarded_infoes_api_controller_1_1_user_boarded_info_message.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserBoardingInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_boarding_info.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserChangeState", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_change_state.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserForAuthentication", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_for_authentication.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserLocation", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_location.html", null ],
    [ "Traveller_Server.Controllers.UserLocationsApiController.userLocationMessage", "class_traveller___server_1_1_controllers_1_1_user_locations_api_controller_1_1user_location_message.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserResetPassword", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_reset_password.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserRouteTracking", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_route_tracking.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserStatus", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_status.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserStopInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_stop_info.html", null ],
    [ "Traveller_Server.Controllers.UserStopInfoesApiController.UserStopInfoMessage", "class_traveller___server_1_1_controllers_1_1_user_stop_infoes_api_controller_1_1_user_stop_info_message.html", null ],
    [ "Traveller_Server.Models.DataClasses.UserSuspension", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_suspension.html", null ],
    [ "Traveller_Server.Models.DataClasses.GTFSRealtime.VehiclePosition", "class_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_realtime_1_1_vehicle_position.html", null ]
];