var namespace_traveller___server_1_1_models_1_1_data_classes =
[
    [ "GTFS", "namespace_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s.html", "namespace_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s" ],
    [ "GTFSRealtime", "namespace_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_realtime.html", "namespace_traveller___server_1_1_models_1_1_data_classes_1_1_g_t_f_s_realtime" ],
    [ "ActivityLog", "class_traveller___server_1_1_models_1_1_data_classes_1_1_activity_log.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_activity_log" ],
    [ "Alert", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert" ],
    [ "AlertRatingInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert_rating_info.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert_rating_info" ],
    [ "AlertVote", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert_vote.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_alert_vote" ],
    [ "AuthResponse", "class_traveller___server_1_1_models_1_1_data_classes_1_1_auth_response.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_auth_response" ],
    [ "Course", "class_traveller___server_1_1_models_1_1_data_classes_1_1_course.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_course" ],
    [ "CourseRoute", "class_traveller___server_1_1_models_1_1_data_classes_1_1_course_route.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_course_route" ],
    [ "CurrentlyBoardedUser", "class_traveller___server_1_1_models_1_1_data_classes_1_1_currently_boarded_user.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_currently_boarded_user" ],
    [ "FavoritePlace", "class_traveller___server_1_1_models_1_1_data_classes_1_1_favorite_place.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_favorite_place" ],
    [ "Location", "class_traveller___server_1_1_models_1_1_data_classes_1_1_location.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_location" ],
    [ "ResetPasswordLog", "class_traveller___server_1_1_models_1_1_data_classes_1_1_reset_password_log.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_reset_password_log" ],
    [ "TimeSpentWeek", "class_traveller___server_1_1_models_1_1_data_classes_1_1_time_spent_week.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_time_spent_week" ],
    [ "User", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user" ],
    [ "User_Course", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user___course.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user___course" ],
    [ "UserBoardedInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_boarded_info.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_boarded_info" ],
    [ "UserBoardingInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_boarding_info.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_boarding_info" ],
    [ "UserChangeState", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_change_state.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_change_state" ],
    [ "UserForAuthentication", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_for_authentication.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_for_authentication" ],
    [ "UserLocation", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_location.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_location" ],
    [ "UserResetPassword", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_reset_password.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_reset_password" ],
    [ "UserRouteTracking", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_route_tracking.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_route_tracking" ],
    [ "UserStatus", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_status.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_status" ],
    [ "UserStopInfo", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_stop_info.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_stop_info" ],
    [ "UserSuspension", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_suspension.html", "class_traveller___server_1_1_models_1_1_data_classes_1_1_user_suspension" ]
];